packages:
  - apps/*
  - packages/*

allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  prisma: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - esbuild
  - lmdb
  - msgpackr-extract
  - prisma
  - unrs-resolver
